ToDo/ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

ToDo/base/urls.py
from django.urls import path
from base.views import Home, UpdatePage, DeletePage

app_name = 'base'
urlpatterns =[
    path('', Home, name='index'),
    path('update/<int:pk>/', UpdatePage, name="update"),
    path('delete/<int:pk>/', DeletePage, name='delete'),
]

ToDo/base/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=500)
    done = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ToDo/base/forms.py
from django import forms
from base.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

ToDo/base/views.py
from django.shortcuts import render, redirect
from base.models import Task
from base.forms import TaskForm
# Create your views here.

def Home(request):
    tasks = Task.objects.all()
    forms = TaskForm()
    if request.method == "POST":
        forms = TaskForm(request.POST)
        if forms.is_valid():
            forms.save()
        return redirect('/')
    context = {"tasks": tasks, 'forms': forms}
    return render(request, 'base/home.html', context)

def UpdatePage(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')
    context={"form":form}
    return render(request, 'base/update.html', context)

def DeletePage(request, pk):
    task = Task.objects.get(id=pk)
    if request.method == "POST":
        task.delete()
        return redirect('/')
    context={'task': task}
    return render(request, 'base/delete.html', context)

ToDo/base/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr" id="particles-js">
  <head>
    <meta charset="utf-8">
    <title>To Do app</title>
    <!-- custom style  -->
    <link rel="stylesheet" href={% static "/css/style.css" %}>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="main">
      <div class="container home">
        {%block body_block%}
        {% endblock %}
      </div>
    </div>

  <script type="text/javascript" src="{% static "/js/particles.min.js" %}" ></script>
  <script src="{% static "/js/script.js" %}"></script>


  </body>
</html>

ToDo/base/templates/base/delete.html
{% extends 'base/base.html' %}
{% block body_block %}
<div class="card w-100">
<div class="card-body">
  <h5 class="card-title">Delete Task</h5>
  <p class="card-text">are you sure you want to delete this task?</p>
  <form action='' method="POST">
    {% csrf_token %}
    <p>{{Task}}</p>
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>
</div>
</div>
{% endblock %}

ToDo/base/templates/base/home.html
{% extends 'base/base.html' %}

{% block body_block %}
  <h1>Welcome</h1>
  <p> add task</p>
  <form method="POST" action="{% url "base:index" %}">
    {% csrf_token %}
    {{forms.name}}
    <input class="btn btn-warning" type="submit" name="add task" value="Add">
  </form>
  <div class="card " style="width: 30rem;">
  <ul class="list-group list-group-flush">
    {% for task in tasks %}

      <li class="list-group-item task">
      {% if task.done is True%}

        <strike>{{task}}</strike>
      {% else%}
        {{task}}
      {% endif%}
      <a class="btn btn-outline-primary" href="{% url "base:update" task.id %}">Update</a>
      <a class="btn btn-outline-danger" href="{% url "base:delete" task.id %}">Delete</a>
      </li>
    {% endfor%}

  </ul>
</div>

{% endblock %}

ToDo/base/templates/base/update.html
{% extends 'base/base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h2>Update Task</h2>

  <form action='' method="POST">
    {% csrf_token %}
    {{form.name}}
    <p>Done: {{form.done}}</p>
    
    <input class='btn btn-primary' type="submit"  value="Edit">
  </form>
</div>
{% endblock %}